### ISSUE TITLE
Animation Of Player

### ISSUE THREAD

**Issue by nwrenger** [NWrenger/Crastination#1]
The Animation of Player must be moved in a new Script, the Player.gd Script is to full of junk.

**Comment by NWrenger** [comment]
#[1786a95](https://github.com/NWrenger/darkplate/commit/1786a9573c37833dc1f8a010978bb8182640e112)

**Comment by nwrenger** [comment]
Did that in commit #[1786a95](https://github.com/NWrenger/darkplate/commit/1786a9573c37833dc1f8a010978bb8182640e112)
